services:
  rabbitmq:
    container_name: 'rabbitmq'
    image: 'rabbitmq:4-management'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=guest'
      - 'RABBITMQ_DEFAULT_USER=guest'
    ports:
      - '5672:5672'
      - '15672:15672'